# Generated by Django 3.2.18 on 2023-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zjyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='birthday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
