# Generated by Django 3.2.18 on 2023-12-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zjyapp', '0002_alter_personalinfo_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Work Experiences',
            },
        ),
    ]
