# Generated by Django 3.2.18 on 2023-12-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zjyapp', '0003_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Introduction',
            },
        ),
    ]
