# Generated by Django 3.2.18 on 2023-12-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zjyapp', '0004_skillintroduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
